trigger:
- main

pool:
  name: 'self-pool-for-mac'

variables:
  DOCKER_IMAGE_NAME: 'joke-backend'
  DOCKER_IMAGE_TAG: $(Build.BuildId) # Use Build ID as a unique tag

steps:
- script: |
    echo "Building Docker image."
    docker build -t $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .
  displayName: 'Build Docker Image'

- script: |
    echo "Tagging and pushing Docker image."
    docker tag $(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) localhost:5000/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)  # localhost:5000 is the URL of the local Docker registry running on our machine.
    docker push localhost:5000/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
    echo "DOCKER_IMAGE=localhost:5000/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)" > build-artifact.txt
  displayName: 'Push Docker Image and Save Artifact'

- publish: build-artifact.txt
  displayName: 'Publish Build Artifact'
